=== Dicelette/core/template.schema.json
{
    "$id": "Dicelette",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Critical": {
            "description": "If the result can be considered as a critical\nCritical is compared to the \"natural\" dice result, so any modifier doesn't count",
            "properties": {
                "failure": {
                    "description": "The value that will be considered as a failure",
                    "title": "failure",
                    "type": "integer"
                },
                "success": {
                    "description": "The value that will be considered as a success",
                    "title": "success",
                    "type": "integer"
                }
            },
            "title": "Critical",
            "type": "object"
        },
        "CustomCritical": {
            "properties": {
                "onNaturalDice": {
                    "description": "If \"true\", the comparison will be made on the natural dice result, without any modifier, including the statistics bonus if any.",
                    "title": "onNaturalDice",
                    "type": "boolean"
                },
                "sign": {
                    "description": "Sign of the comparison",
                    "enum": [
                        "!=",
                        "<",
                        "<=",
                        "=",
                        "==",
                        ">",
                        ">="
                    ],
                    "title": "sign",
                    "type": "string"
                },
                "value": {
                    "description": "Can be a simple value, or a formula, including the statistics with $",
                    "title": "value",
                    "type": "string"
                }
            },
            "required": [
                "sign",
                "value"
            ],
            "title": "CustomCritical",
            "type": "object"
        }
    },
    "properties": {
        "$schema": {
            "description": "Specifies the URL for the schema definition\nThis property is optional and should contain a valid URI.",
            "title": "$schema",
            "type": "string"
        },
        "charName": {
            "description": "Allow to force the user to choose a name for them characters",
            "title": "charName",
            "type": "boolean"
        },
        "critical": {
            "$ref": "Dicelette#/definitions/Critical",
            "description": "How the success/echec will be done",
            "title": "critical"
        },
        "customCritical": {
            "additionalProperties": {
                "$ref": "Dicelette#/definitions/CustomCritical"
            },
            "description": "Custom critical, allow to adjust the critical on a statistic, and set multiple critical value",
            "maximum": 22,
            "title": "customCritical",
            "type": "object"
        },
        "damage": {
            "additionalProperties": {
                "type": "string"
            },
            "description": "Special dice for damage",
            "maximum": 25,
            "title": "damage",
            "type": "object"
        },
        "diceType": {
            "description": "A dice type in the notation supported by the bot",
            "title": "diceType",
            "type": "string"
        },
        "statistics": {
            "additionalProperties": {
                "properties": {
                    "combinaison": {
                        "description": "The combinaison that can be made with ANOTHER statistic\nAutomatically disable the max/min value",
                        "title": "combinaison",
                        "type": "string"
                    },
                    "max": {
                        "description": "The value of the statistic that can take the stats",
                        "title": "max",
                        "type": "integer"
                    },
                    "min": {
                        "description": "The minimal value of the statistic that can take the stats",
                        "title": "min",
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "description": "The statistics that can be used in the dice throw",
            "maximum": 25,
            "title": "statistics",
            "type": "object"
        },
        "total": {
            "description": "A total can be set, it allows to calculate the total value of a future register member\nIf the sum of the value > total, the bot will send a message to the user to inform him that the total is exceeded and an error will be thrown",
            "title": "total",
            "type": "integer"
        }
    },
    "type": "object"
}

=== Dicelette/core/validation_schema.json
{
	"$schema": "./template.schema.json",
	"diceType": "1d40+$>40",
	"statistics": {
		"Force": {
			"max": 40,
			"min": 5
		},
		"Endurance": {
			"max": 40,
			"min": 5
		},
		"Dextérité": {
			"max": 40,
			"min": 5
		},
		"Intelligence": {
			"max": 40,
			"min": 5
		},
		"Charisme": {
			"max": 40,
			"min": 5
		},
		"Technique": {
			"max": 40,
			"min": 5
		},
		"Point de vie": {
			"combinaison": "(force+endurance)*2"
		}
	},
	"critical": {
		"failure": 1,
		"success": 40
	},
	"total": 130,
	"damage": {
		"Force": "1d{{round(force/4)}}",
		"Endurance": "1d{{round(endurance/4)}}",
		"Dextérité": "1d{{round(dextérité/4)}}",
		"Intelligence": "1d{{round(intelligence/4)}}",
		"Charisme": "1d{{round(charisme/4)}}",
		"Technique": "1d{{round(technique/4)}}"
	},
	"customCritical": {
		"Hard success": {
			"sign": "<=",
			"value": "round($/5)",
			"onNaturalDice": false
		}
	}
}
